#CyHV3_ORF5_1    [['8606', '9949']]      9457    9474    -17     DEL      1
# CyHV3_ORF25     [['45570', '47375']]    47346   49196   -1850   DEL     1
#CyHV3_ORF26     [['47474', '47644']]    47346   49196   -1850   DEL     1
#CyHV3_ORF27     [['48534', '48740']]    47346   49196   -1850   DEL     1
#CyHV3_ORF40     [['60044', '60598']]    60281   60306   -25     DEL     4
#CyHV3_ORF69     [['132865', '134445']]  133271  133283  -12     DEL     3
#CyHV3_ORF78     [['142353', '144593']]  143509  143533  -24     DEL     3
#CyHV3_ORF84     [['153583', '155916']]  155446  155479  -33     DEL     4
#CyHV3_ORF148    [['253956', '255779']]  254131  254149  -18     DEL     4)

interval_sv = [143509, 143533]
seq_ORF_78 = "ATGGCCCCTCATCTTCGAAGTCGTTCACTCACCGCGCGGCACCTTACTGAGTCCCGCACGGAGGGGCTCAGCTTCCACGGCCAGCGCCCCGACGGAACCATACTGGCCGTGGACAGGGGCAGGCTGCTCTGCACGCACGCCGACATCGACGAGCTCGAGCGCACCCTCCTCGGCTCCTCTGCCCCCGTGAGCCACAAAGACCTGGTCCCCATCTACTGCGACCGCTGCCTGCCCTACACTCTGCCCTGGTCCCAGGCTCCCGTCTCCCATGACCGCGACGGCCTCCTGCCCGCTCACGGGTACACCGTCGTGGGCACCGCCGGCGTCTTCTCCAGGGACCTGGTGGAGACCAAGGGCATGGAGAAGACGTCCCAGCACTACCACCTGCCCCTGCGGGACCTCGAGCTCTTCACCCACACTCAGAAGAGCAACCGCGTGCTGTTGGTGCACTGCGACATCCCCATTGGCTCCGTAATCTGCTATTGGCACGTACACGACAGGGAAAACGCGCACTGCGCCGTCAACGCTCTGATTGTCATCACCGACCAGGCCTTCCACACCATCTTCTCGAGGTGCAAGGGGCTCAGTTGGACGACTACCTCGGTGGTGGCCAGCGAGCTGTCTCTGGTCGGGATCCCCGGCCGCGCTTCCAGCCTCATCCACAGCATCAGCAGGCTCTCGGACCTCACGCAGGGCACCCTGCCCGTATCGCGCAAACCCGACCTCAGGTCCCTGGGCTACGGCCGCAACTCTCCGCGACACGCCGACGTCGTCATGGCGGCGCTCAGCAAGGGCACGGAGAACCCCGAGGAGACGGCCAGCGATCAGAGGAGAGAGTGGAAGCAGATGGTGGAGATGCTCATGGGCCAGCTGGACCTCCTCTACGAGGCCACCATCGCGAAGGGCCCAGACGACGACGGCCAGGCCAGCAAAAGATATTTAAGCGAGGGCCGCGACCTGTTTAAAAAACTCCACGAGCTCAAGGCCCATCTTGAGAAGCTCGAGTCTGCCTCAACCCCTGCCGCAGTATCAGCAGCAGCACCAGCACCCTCAACCTCAGTACCCGCGCCGCAGCAGACGACCGAGACGCCAAAAGAAGATTCCCGAGCAGGAACCCCAGAAGCCTCGGTCACATCTCAGCAGGCTCAGTCAGCTCCTGTACCCTCTCAACCGGTAACCTCTGTACCCTCTCAACCGGTAACCTCTGTACCCTCTCAACCGGTAACCTCTGTACCCTCTCAACCGGTAACCTCTGTACCCTCTCAACCGGTAACCTCTGTACCCTCTCAACCGGTAACCTCTGTACAACAACCCAATAAGATGGCCAGCTCAGACGACATTCGCGACGCCGTCGCCAAGGCACTCGCCGACGTGATCAAGCCTTCCATCCAGCAATACACTCCTCCACCCCAGCCCAACCACGGCGGCGGAGCGACGGGGTTCAGGGACTTTGTCGAGATGTTCAAGCTCATGCAGCAGATGCACGCTCCGGCTCAGGCCCCCGCACCCGTTGCGGCCCCTGCTCCCGTGGTGGCCCAGGTTCCCCAGTCCCTGTCGCACCACGGGCTGGTGGACGACGAACACCCTTCCACCTCGGCTCACCAGAGAGGAGGCAAGCGCAAGCTGGAGCTGTCTGACGATGACATCAAGCTGTTTAAGAAGCTGAGGGAGCAAGACGAGCTCAGCCGGCGCGAGAAGGAGCGCCTGGCCCTCAAAGAGGAGCTCAAGAAAGAGATGATGGCCGAGTTCTCCTCCTCCGTACCTCAAGCAGCGGCACCCGTGGTTGTACCCTCTACCTCAGCACCAGCACCCGTCACCGACGTGAAGCAGCTGGTGAGCGAGGCCATCAAGGAGCTGCTCGCCGTCCAGCAGCAGCAACAGCAGCAAGCCGTGGTGCCGGCTCCCCAGGGAGTCCCGGGTCCCGCCACCACCATCTCCCTTCCAGTGGCCACCCTGGCCGCGGCCACAGGCAGATCACCCGCAGCCGCAGCGGCACTCCAGAGCGCCATCAACAACGTACACGAGTCGGCCAGCCAGCTGGTCCCCGGCGGCCTCAACCTCGGAGTCGCCGGCGTGCCCGTCAACGCGTCGACCGTCGTGAGCACACCACAACCCGCTGTACCCTCCACATCAACCCAGGTCGTCTCAGTCTCGGCGGGGCTCGAGGTCCAGGGCGGCGGCAACAAGAAATCCCTCAACGACGACGCCCGCAAGATGATGATGCTGATGATGGACCACTAG"
pos_debut_cl = [142353]
ORF_78 =[142353, 144593]
mut_ORF_78 =[143509,143533]


pos_debut_mut = mut_ORF_78[0]-ORF_78[0]+1
pos_fin_mut = mut_ORF_78[1]-ORF_78[0]+1
print (pos_debut_mut,pos_fin_mut)
seq_ORF_mut=""
for i in range (len(seq_ORF_78)):
    if pos_debut_mut>i+1 or pos_fin_mut<i+1:
        seq_ORF_mut+=(seq_ORF_78[i])

print (seq_ORF_mut)

for i in range (len(seq_ORF_78)):
    if pos_debut_mut>i+1 or pos_fin_mut<i+1:
        seq_ORF_mut+=(seq_ORF_78[i])

